from app.models import db, Product


def seed_products():

    short_sword = Product(title="Short Sword", image="https://images.unsplash.com/photo-1440711085503-89d8ec455791?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8c3dvcmR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60", price=200, description="A sword for only the very bravest of heros. It is for the Hero who is not afraid to get up close and personal with the maw of the beast. Light versital and ready for any close combat you can throw at it.", lore="It was written by a master swordsman once that a warriors true mettle could only be found when wielding a short sword.", quantity=2000, category_id=1),
    long_sword = Product(title="Long Sword", image="http://www.pngall.com/wp-content/uploads/2016/03/Sword-Free-Download-PNG.png", price=300, description="A sword perfect for your assault class hero. It can stand up to heavy blows from mid-level weapons and yet still be versitile enough to leap into the fold. This blade is deadly in a fight against lightly armoured foes and multiple enemy engagements.", lore="Empires have been one and lost depending on which end of the long sword you found yourself on.", quantity=1467, category_id=1)
    broad_sword = Product(title="Broad Sword", image="", price=500, description="This weapon is designed to counter heavily armoured enemies. It is also helpful in cutting a path through an enemy hoard. It is slow, heavy and will decimate anything in its path.", lore="It is said that when the realm of man was told they would face the armored hoards of Sauron, they responded with the broad sword.", quantity=1298, category_id=1)
    dagger = Product(title="Dagger", image="", price=150, description="If you are looking for fast look no farther than the dagger. This weapon will slice dice and cut POTATOES faster than you can say Bererland.", lore="Strike fast and move quickly is the code of the dagger.", quantity=5000, category_id=1)
    elven_dagger = Product(title="Elven Dagger", image="", price=150, description="The back up weapon of the elvish Army. Used Broadly as a secondary to their bows. More nimble than the traditional dagger but only has one edge.", lore="The elvish dagger is considered a short weapon. Not because of its size but because its target only sees it for a short time before they expire.", quantity=419, category_id=1)
    hook_sword = Product(title="Hook_sword", image="", price=325, description="A sword with surprising multiplicity. It is between the long sword and short sword in length. It has a sharpened point on the end of the backside of the blade that is used to puncture hard targets and pull them.", lore="Its not much to look at but you can use it anywhere.", quantity=10000, category_id=1)
    falchion = Product(title="Falchion", image="", price=500, description="Similar to the broad sword in speed but heavier and more special", lore="", quantity=1298, category_id=1)
